"""add unique constraint on 'Package.name'

Revision ID: eb57a14bb3af
Revises: c252d06d44b8
Create Date: 2023-09-02 12:48:01.848884

"""
from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb57a14bb3af"
down_revision: str | None = "c252d06d44b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dofi_package") as batch_op:
        batch_op.create_unique_constraint("uq_dofi_package_name", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dofi_package") as batch_op:
        batch_op.drop_constraint(constraint_name="uq_dofi_package_name", type_="unique")
    # ### end Alembic commands ###
