name: Python package

on:
    pull_request:
        branches:
            - main

env:
    PYTHON_VERSION: 3.11

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Install Python and Poetry
                uses: ./.github/actions/poetry
                with:
                    python-version: ${{ env.PYTHON_VERSION }}
            -   name: Lint & Format
                run: |
                    make lint
    test:
        runs-on: ubuntu-latest

        needs: lint
        steps:
            -   uses: actions/checkout@v3
            -   name: Install Python and Poetry
                uses: ./.github/actions/poetry
                with:
                    python-version: ${{ env.PYTHON_VERSION }}
            -   name: Run Pytest
                run: |
                    make test

    # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#packaging-workflow-data-as-artifacts
    coverage:
        runs-on: ubuntu-latest

        needs: lint
        steps:
            -   uses: actions/checkout@v3
            -   name: Install Python and Poetry
                uses: ./.github/actions/poetry
                with:
                    python-version: ${{ env.PYTHON_VERSION }}
            -   name: Run Pytest
                run: |
                    make coverage
